name: page_indicator_plus
description: A Flutter package that provides a simple and customizable page indicator.
version: 1.0.4
homepage: https://github.com/Johnnyfdev/page_indicator_plus

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
